sprint6: &sprint6
  - httpq: package-release-2.2.5.0-212
  - webhook003: jenkins-55
  - apimgr: jenkins-222
sprint7: &sprint7
  - httpq: package-release-2.2.7.0-212
  - webhook003: jenkins-55
  - apimgr: jenkins-222

qa1: 
  <<: *sprint6
prod: 
  <<: *sprint6
imp1: 
  <<: *sprint7
